/* One-tab scenarios: compatible shared values + isolated model inputs, explicit JSON files. */
(() => {
 const M=HorizonScenarioModel,S=HORIZON_SCENARIO_SCHEMA,$=id=>document.getElementById(id);
 const name=document.documentElement.dataset.horizonPage,active=Object.hasOwn(S.views,name),key='horizon-scenario-v1:'+new URL('.',location.href).pathname;
 let state=M.create(),loaded=false,restoring=false,status='ready',importToken=0,storageOK=true;
 const copy=x=>JSON.parse(JSON.stringify(x)),en=()=>document.documentElement.lang==='en';
 const text={title:['Senaryo','Scenario'],note:['Ortak girdiler bu sekme oturumunda tutulur; sunucuya veya URL’ye gönderilmez. Dosyaya kaydetmek isteğe bağlıdır.','Shared inputs stay in this tab session; they are not sent to a server or URL. Saving a file is optional.'],date:['Başlangıç tarihi (tarih kullanan modeller)','Start date (models that use dates)'],budget:['Toplam başlangıç kaynağı (AZN)','Total initial resources (AZN)'],rate:['Kur: 1 EUR için AZN','Exchange rate: AZN per 1 EUR'],scope:['Dil hedefi, belgeli dil ve iş teklifi eşdeğer değildir; rota/model alanlarında ayrı korunur. Diğer para birimleri modeldeki tarihli kur referansını kullanır.','Language targets, certified language and job offers are distinct; they remain scoped to their route/model. Other currencies use the model’s dated rate reference.'],export:['JSON dışa aktar','Export JSON'],import:['JSON geri yükle','Import JSON'],reset:['Senaryoyu sıfırla','Reset scenario'],ready:['Senaryo bu sekmede hazır.','Scenario ready in this tab.'],saved:['Senaryo dosyası indirildi.','Scenario file downloaded.'],imported:['Senaryo dosyası geri yüklendi.','Scenario file restored.'],resetDone:['Senaryo başlangıç varsayımlarına sıfırlandı.','Scenario reset to starting assumptions.'],invalid_schema:['Dosya veya alanlar şemaya uymuyor. Mevcut form değiştirilmedi.','The file or inputs do not match the schema. The current form was not changed.'],invalid_json:['Geçerli bir JSON senaryo dosyası seç. Mevcut form değiştirilmedi.','Choose a valid JSON scenario file. The current form was not changed.'],unsupported_version:['Bu senaryo sürümü desteklenmiyor. Mevcut form değiştirilmedi.','This scenario version is not supported. The current form was not changed.'],file_too_large:['Dosya 256 KB sınırını aşıyor. Mevcut form değiştirilmedi.','The file exceeds 256 KB. The current form was not changed.'],storage:['Bu tarayıcı sekme kaydını engelliyor; geçişte koruma için JSON dosyası kullan.','This browser blocks tab storage; use a JSON file to preserve inputs between pages.'],invalid_inputs:['Dışa aktarmadan önce geçersiz alanları düzelt.','Fix invalid inputs before exporting.']};
 const t=k=>(text[k]||text.invalid_schema)[en()?1:0],labels=[];
 function caption(node,k){labels.push([node,k]);node.textContent=t(k);return node;}
 const panel=document.createElement('details');panel.id='scenario-settings';panel.className='scenario-settings';caption(panel.appendChild(document.createElement('summary')),'title');caption(panel.appendChild(document.createElement('p')),'note');
 const controls=panel.appendChild(document.createElement('div'));controls.className='scenario-common-fields';
 for(const[id,k,type]of [['scenario-date','date','date'],['scenario-budget','budget','number'],['scenario-rate','rate','number']]){const label=controls.appendChild(document.createElement('label'));caption(label.appendChild(document.createElement('span')),k);const node=label.appendChild(document.createElement('input'));node.id=id;node.type=type;if(type==='number'){node.min=id==='scenario-rate'?'.0001':'0';node.step='any';node.max=id==='scenario-rate'?'1000000':'1000000000000';}}
 caption(panel.appendChild(document.createElement('p')),'scope');const actions=panel.appendChild(document.createElement('div'));actions.className='scenario-actions';
 for(const[id,k]of [['scenario-export','export'],['scenario-import','import'],['scenario-reset','reset']]){const b=actions.appendChild(document.createElement('button'));b.id=id;b.type='button';caption(b,k);}
 const fileLabel=panel.appendChild(document.createElement('label'));caption(fileLabel.appendChild(document.createElement('span')),'import');fileLabel.hidden=true;fileLabel.style.display='none';const file=fileLabel.appendChild(document.createElement('input'));file.id='scenario-file';file.type='file';file.accept='.json,application/json';file.hidden=true;
 const message=panel.appendChild(document.createElement('p'));message.id='scenario-status';message.setAttribute('role','status');message.setAttribute('aria-live','polite');$('horizon-settings').append(panel);
 // Cross-view funding can include fractional AZN after conversion.
 if(name==='pusula')$('budget').step='any';if(name==='index')$('initial_cash').step='any';
 function fields(strict=false){const result={};if(!active)return result;for(const[id,spec]of Object.entries(S.views[name])){const node=$(id);if(!node)throw Error('Missing scenario input: '+name+'.'+id);if(spec.type==='number'){if(!node.value)result[id]=null;else if(!node.checkValidity()){if(strict)throw Error('invalid_inputs');result[id]=null;}else result[id]=Number(node.value);}else if(spec.type==='date'){if(!node.value||!M.date(node.value)){if(strict&&node.value)throw Error('invalid_inputs');result[id]=null;}else result[id]=node.value;}else result[id]=node.value;}return result;}
 const initial=active?{fields:fields(),...(window.HorizonView.captureExtra?.()||{})}:null;
 function shared(f,base){const c=copy(base);if(!active)return c;if(name==='germany'||name==='work')c.start_date=f.start_date;
  if(name==='germany'){c.azn_per_eur=f.azn_per_eur;c.budget_azn=f['budget-mode']==='sources'?(f.savings_azn===null?null:f.savings_azn+Number(f.rotating_branch)):(f.initial_liquid===null||f.blocked_initial===null||c.azn_per_eur===null?null:Number(((f.initial_liquid+f.blocked_initial)*c.azn_per_eur).toFixed(4)));}
  if(name==='work')c.budget_azn=f.budget_azn;if(name==='pusula')c.budget_azn=f.budget;
  if(name==='index'){const rate=M.rate(S.routeCurrencies[f.route],c);c.budget_azn=f.initial_cash===null||rate===null?null:Number((f.initial_cash*rate).toFixed(4));}return c;}
 function capture(strict=false,updateCommon=false){if(!active)return;const f=fields(strict);if(updateCommon)state.common=shared(f,state.common);state.views[name]={fields:f,shared:copy(state.common),...(window.HorizonView.captureExtra?.()||{})};}
 function display(){for(const[n,k]of labels)n.textContent=t(k);$('scenario-date').value=state.common.start_date||'';$('scenario-budget').value=state.common.budget_azn??'';$('scenario-rate').value=state.common.azn_per_eur??'';message.textContent=t(storageOK?status:'storage');message.classList.toggle('error',['invalid_schema','invalid_json','unsupported_version','file_too_large','invalid_inputs'].includes(status));}
 function save(){let payload;try{payload=M.stringify(state);}catch{status='invalid_inputs';display();return;}try{sessionStorage.setItem(key,payload);storageOK=true;}catch{storageOK=false;}display();}
 function overlay(f,previous,c){const changed=k=>!previous||previous[k]!==c[k];
  if((name==='germany'||name==='work')&&changed('start_date'))f.start_date=c.start_date;
  if(name==='work'&&changed('budget_azn'))f.budget_azn=c.budget_azn;
  if(name==='pusula'&&changed('budget_azn'))f.budget=c.budget_azn;
  if(name==='index'&&(changed('budget_azn')||changed('azn_per_eur'))){const rate=M.rate(S.routeCurrencies[f.route],c);f.initial_cash=c.budget_azn===null||rate===null?null:Number((c.budget_azn/rate).toFixed(6));}
  if(name==='germany'&&(changed('budget_azn')||changed('azn_per_eur'))){f.azn_per_eur=c.azn_per_eur;f['budget-mode']='allocation';const total=c.budget_azn===null||c.azn_per_eur===null?null:c.budget_azn/c.azn_per_eur;f.blocked_initial=total===null?null:Number(Math.min(total,11904).toFixed(2));f.initial_liquid=total===null?null:Number(Math.max(0,total-11904).toFixed(2));}return f;}
 function restore(){if(!active)return;const view=state.views[name],f=overlay(copy(view?.fields||initial.fields),view?.shared,state.common);restoring=true;try{HorizonView.restore(f,view||initial);}finally{restoring=false;}capture();}
 function edit(event){if(restoring||!active)return;try{const id=event?.target?.id;if(name==='index'&&id==='route'){const f=overlay(fields(),null,state.common);restoring=true;try{HorizonView.restore(f);}finally{restoring=false;}}const commonIds={germany:['start_date','azn_per_eur','budget-mode','savings_azn','rotating_branch','initial_liquid','blocked_initial','apply-budget'],work:['start_date','budget_azn'],pusula:['budget','funding'],index:['initial_cash']};capture(false,commonIds[name]?.includes(id));save();}catch{status='invalid_inputs';display();}}
 try{const stored=sessionStorage.getItem(key);if(stored){state=M.parse(stored);loaded=true;}}catch{try{sessionStorage.removeItem(key);}catch{}status='invalid_schema';}
 if(active){if(loaded)restore();else capture(false,true);save();}else display();
 for(const id of ['scenario-date','scenario-budget','scenario-rate'])$(id).addEventListener('input',()=>{const c=copy(state.common),node=$(id),value=node.value;const k={'scenario-date':'start_date','scenario-budget':'budget_azn','scenario-rate':'azn_per_eur'}[id];if(value&&!node.checkValidity()||(k==='start_date'&&value&&!M.date(value))){status='invalid_inputs';message.textContent=t(status);return;}c[k]=value?(k==='start_date'?value:Number(value)):null;const next={...state,common:c};try{M.validate(next);state=next;restore();status='ready';save();}catch{status='invalid_inputs';display();}});
 document.addEventListener('input',e=>{if(e.target.closest('main'))edit(e);});document.addEventListener('change',e=>{if(e.target.closest('main'))edit(e);});document.addEventListener('click',e=>{if(e.target.closest('main button'))queueMicrotask(()=>edit({target:e.target.closest('main button')}));});window.addEventListener('pagehide',()=>{if(active){try{capture();sessionStorage.setItem(key,M.stringify(state));}catch{}}});
 document.addEventListener('horizon:preferences',display);
 $('scenario-export').addEventListener('click',()=>{try{capture(true);const payload=M.stringify(state),blob=new Blob([payload],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='horizon-scenario-v1.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status='saved';save();}catch(error){status=error.message==='invalid_inputs'?'invalid_inputs':error.code||'invalid_schema';display();}});
 $('scenario-import').addEventListener('click',()=>file.click());file.addEventListener('change',async()=>{const chosen=file.files[0],token=++importToken;if(!chosen)return;let applied=false;const previous=copy(state),previousFields=active?{fields:fields(),...(HorizonView.captureExtra?.()||{})}:null;try{if(chosen.size>M.MAX_BYTES)throw Object.assign(Error('file_too_large'),{code:'file_too_large'});const next=M.parse(await chosen.text());if(token!==importToken)return;applied=true;state=next;restore();M.validate(state);status='imported';save();}catch(error){state=previous;if(applied&&active){restoring=true;try{HorizonView.restore(previousFields.fields,previousFields);}finally{restoring=false;}}status=error.code||'invalid_schema';display();}finally{file.value='';}});
 $('scenario-reset').addEventListener('click',()=>{importToken++;state=M.create();restoring=true;try{if(active)HorizonView.restore(copy(initial.fields),initial);}finally{restoring=false;}capture(false,true);status='resetDone';try{sessionStorage.removeItem(key);}catch{}if(active)save();else display();});
 window.HorizonScenario={snapshot(){capture(true);return M.validate(state);},getStorageKey:()=>key};document.documentElement.classList.remove('horizon-initializing');
})();
