'use strict';
const d=WORK_DATA,$=id=>document.getElementById(id),money=(v,c='AZN')=>new Intl.NumberFormat('tr-TR',{maximumFractionDigits:0}).format(v)+' '+c;
function el(tag,text,parent,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(parent)parent.append(n);if(cls)n.className=cls;return n;}
const labels={start_date:'Ana başlangıç tarihi',additional_departure_delay_months:'Ek askerlik/çıkış gecikmesi, ay',bridge_months:'Ana tarihten sonra deneyim köprüsü, ay',budget_azn:'Gelecek brüt bütçe, AZN',degree_completed:'Lisans tamamlanmış varsayımı',degree_recognized:'Rotanın istediği diploma tanınması',legal_departure_verified:'Yasal çıkış / askerlik uygunluğu',offer_available:'Seçili rotaya uygun iş teklifi',job_requirements_verified:'İş / meslek / sözleşme koşulları',sponsor_approved:'İşveren sponsor / izin süreci',experience_months:'İlgili ücretli deneyim, ay',experience_qualifies_verified:'Deneyim rotanın ölçütlerine uyuyor',annual_gross_salary_local:'Teklif yıllık brüt maaş, yerel para',salary_rule_verified:'Going-rate ve diğer ücret şartları',local_language_certified_cefr:'Hedef ülke dili, belgeli CEFR',english_certified_cefr:'İngilizce, belgeli CEFR',english_clb:'Dört becerinin en düşük CLB değeri',selection_or_invitation_confirmed:'Davet / kota seçimi',extra_route_requirements_verified:'Rotanın diğer tüm şartları',funds_documented:'Kullanılabilir fon belgeleri',financial_proof_exemption_verified:'Finansman kanıtı muafiyeti / alternatif',funds_unencumbered_verified:'Fon borçsuz / taahhütsüz şartına uygun',authority_approval_confirmed:'İlgili kurum çalışma onayı',route_points:'Seçili rotanın kendi puan toplamı',points_calculation_verified:'Puan hesabı ve belgeleri doğrulandı',setup_cost_local:'Vize / depozito / taşınma toplamı, yerel para',monthly_expense_local:'Aylık toplam gider, yerel para',monthly_net_pay_local:'Aylık kullanılabilir net gelir, yerel para',months:'Nakit ufku, ay',income_start_month:'İş gelirinin kazanılmaya başladığı ay',pay_delay_months:'Ödeme gecikmesi, ay',job_loss_month:'İş kaybı başlangıç ayı',job_loss_months:'İş kaybı / toparlanma süresi, ay',annual_expense_growth:'Yıllık gider artışı, 0–1',reserve_months:'Dokunulmayacak rezerv, ay',repayment_monthly_azn:'Dönüşümlü katkı, AZN/ay',repayment_months:'Katkı ödenen ay sayısı'};
labels.employer_entry_policy_verified='Giriş yılındaki H1B işveren ödeme / muafiyet politikası';
const basic=['start_date','budget_azn','experience_months','bridge_months','additional_departure_delay_months','annual_gross_salary_local','local_language_certified_cefr','english_certified_cefr','english_clb','route_points'];
const cash=['setup_cost_local','monthly_expense_local','monthly_net_pay_local','months','income_start_month','pay_delay_months','job_loss_month','job_loss_months','annual_expense_growth','reserve_months','repayment_monthly_azn','repayment_months'];
const tris=Object.keys(d.defaults).filter(k=>typeof d.defaults[k]==='boolean'||(d.defaults[k]===null&&!basic.includes(k)&&!cash.includes(k)));
for(const [k,v] of Object.entries(d.defaults)){
 if(k==='kind')continue;const parent=$(basic.includes(k)?'basic':cash.includes(k)?'cash-inputs':'verification'),label=el('label',labels[k]||k,parent);let node;
 if(tris.includes(k)){node=el('select',undefined,label);for(const [value,text] of [['null','Bilinmiyor'],['true','Evet / varsay'],['false','Hayır']]){const o=el('option',text,node);o.value=value;}node.value=String(v);}
 else if(k.includes('certified_cefr')){node=el('select',undefined,label);for(const level of ['null','A1','A2','B1','B2','C1','C2']){const o=el('option',level==='null'?'Belge bilinmiyor':level,node);o.value=level;}node.value=v||'null';}
 else {node=el('input',undefined,label);node.type=k==='start_date'?'date':'number';if(node.type==='number'){node.min='0';node.step=k==='annual_expense_growth'?'0.01':'any';}node.value=v===null?'':v;}
 node.id=k;node.addEventListener('input',calculate);
}
for(const [id,c] of Object.entries(d.countries)){const o=el('option',c.name_tr,$('country'));o.value=id;}
function selected(){return d.routes.find(r=>r.id===$('route').value);}
function inputs(){const p={...d.defaults};for(const k of Object.keys(p)){if(k==='kind')continue;const raw=$(k).value;if(tris.includes(k))p[k]=JSON.parse(raw);else if(k.includes('certified_cefr'))p[k]=raw==='null'?null:raw;else if(k==='start_date')p[k]=raw;else {if(!raw.trim()&&d.defaults[k]!==null)throw Error('Zorunlu sayı boş: '+labels[k]);p[k]=raw.trim()?Number(raw):null;}}return p;}
function populate(){const list=d.routes.filter(r=>$('country').value==='all'||r.country_id===$('country').value);$('route').replaceChildren();list.forEach(r=>{const o=el('option',r.country_id+' · '+r.name_tr,$('route'));o.value=r.id;});if(list.some(r=>r.id==='DE-SKILLED-ACADEMIC-JOB'))$('route').value='DE-SKILLED-ACADEMIC-JOB';changeRoute();}
function changeRoute(){
 const r=selected(),c=d.countries[r.country_id];
 for(const k of [...tris,'annual_gross_salary_local','setup_cost_local','monthly_expense_local','monthly_net_pay_local','route_points','local_language_certified_cefr'])$(k).value=d.defaults[k]===null?(tris.includes(k)||k.includes('cefr')?'null':''):String(d.defaults[k]);
 const info=$('route-info');info.replaceChildren();el('h3',r.name_tr,info);el('p',c.name_tr+' · yerel para '+c.currency+' · '+r.route_type+' · kaynak kontrolü '+r.checked_date,info,'muted');
 for(const text of [r.new_graduate_summary,r.experience_scope,r.salary_scope,r.language_requirements,r.recognition_requirements,r.financial_proof.scope])el('p',text,info);
 const details=$('route-detail');details.replaceChildren();el('p',r.permit_duration_summary,details);el('p',r.settlement_summary,details);r.risks.forEach(t=>el('p',t,details,'warn'));
 $('sources').replaceChildren();for(const url of r.sources){const li=el('li',undefined,$('sources')),a=el('a',url,li);a.href=url;a.target='_blank';a.rel='noopener noreferrer';}calculate();
}
function calculate(){
 for(const id of ['result','gates','cash-result','balances','error'])$(id).replaceChildren();
 try{const p=inputs(),r=selected(),out=WorkModel.evaluate(r,d.countries[r.country_id],d.fx,p,d.birth);
 el('p','Senaryo varışı '+out.scenario_departure+' · '+out.scenario_age+' yaş',$('result'),'metric');
 el('p',out.failed_gates.length?'Seçili rotada karşılanmayan kapı var.':out.unknown_gates.length?'Bilinen sayısal engel görünmese de kapılar doğrulanmadı.':'Girilen varsayımlarda modellenen kapılar geçti; izin/onay sonucu değil.',$('result'),'warn');
 const why={departure:'Askerlik/çıkış ve pasaport ayrıca.',degree:'Gelecekte tamamlanmış lisans varsayımı.',recognition:r.recognition_requirements,offer:'Uygun iş teklifi gerekiyor.',job_fit:'Seçili rotanın nitelikli iş/meslek/sözleşme şartları.',sponsor:'İşverenin ilgili izin/sponsor işlemleri.',authority_approval:'İlgili kurum çalışma onayı; davet/kota değil.',experience:r.experience_scope,salary:r.salary_scope,language:r.language_requirements,english_clb:r.language_requirements,selection:'Davet/kota seçimi; havuz/puan yeterli değil.',points:r.points_scope,funds:r.financial_proof.scope,unencumbered_funds:'Brüt20k planın taahhütsüz erişilebilir fon şartı doğrulanmadı.',extra_route_requirements:r.extra_gate_summary};
 why.employer_entry_policy='2026 H1B yurtdışı girişinde uygulanabilir100kUSD işveren ödemesi/muafiyet; mevcut ilan2027-09-21sonrası/2030için garanti değil, giriş yılındaki kural doğrulanmalı.';
 HorizonAlerts.update({kind:'work',title:r.name_tr,items:HorizonAlertsModel.work({route:{...r,currency:d.countries[r.country_id].currency},result:out,inputs:p,why})});
 for(const g of out.gates)el('li',({pass:'Varsayımda geçti',fail:'Karşılanmıyor',unknown:'Bilinmiyor'})[g.status]+' · '+g.key+' — '+(why[g.key]||'Yaş sınırı seçili rota içindir.'),$('gates'),g.status);
 if(out.cash){el('p','Nakit stresi: gerekli kaynak '+money(out.cash.required_azn)+' · açık '+money(out.cash.gap_azn),$('cash-result'),'metric');el('p','İlk negatif ay: '+(out.cash.first_negative_month??'bu senaryoda yok')+' · nakit hesabı yasal kalış/çalışma hakkı vermez.',$('cash-result'),'warn');$('balances').textContent=out.cash.balance.map((v,i)=>'Ay '+i+': '+money(v,out.cash.currency||d.countries[r.country_id].currency)).join('\n');}
 else el('p','Nakit hesabı için yerel kurulum, aylık gider ve kullanılabilir net gelir gerekli; boş alanlar sıfır sayılmadı.',$('cash-result'),'muted');
 }catch(e){$('error').textContent=e.message;HorizonAlerts.update({kind:'work',title:selected()?.name_tr||'İş yolu',items:[{id:'invalid',status:'fail',title:'Geçersiz veya boş girdi',detail:e.message,action:'Hatalı alanı düzelt; eski hesap sonucu geçerli sayılmadı.',target:'start_date'}]});}
}
$('country').onchange=populate;$('route').onchange=changeRoute;$('bridge').onclick=()=>{$('experience_months').value=12;$('bridge_months').value=12;calculate();};populate();

window.HorizonView={restore(fields){$('country').value=fields.country;populate();$('route').value=fields.route;changeRoute();for(const[id,value]of Object.entries(fields))$(id).value=value===null?'':String(value);calculate();}};
